name = "a0b_sensirion_selftest"
description = "A0B Utilities for various Sensirion's sensors selftest"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "sensirion", "sensor"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_sensirion = "*"

[[actions]]
type = "test"
command = ["alr", "build"]
[[actions]]
type = "test"
command = ["bin/selftest"]

[[pins]]
a0b_sensirion = { path='..' }
